### ISSUE TITLE
plz let me in 

### ISSUE THREAD

**Issue by liu-petter** [mathletedev/bender#1]
[Intro]
Put your lovin' hand out, baby
'Cause I'm beggin'

[Chorus]
I'm beggin', beggin' you
So put your loving hand out, baby
I'm beggin', beggin' you
So put your loving hand out, darlin'

**Comment by neowsl** [comment]
Riding high, when I was king
I played it hard and fast, 'cause I had everything
I walked away, but you warned me then
But easy come, and easy go, and it would end
So, any time I bleed, you let me go
Yeah, any time I feed you, get me? No?
Any time I seek, you let me know
But I plan and see, just let me go
